// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZmsUIClient is the client API for ZmsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZmsUIClient interface {
	// ListZoneSpecs returns a list of Availability Zone(s) that can be started through the UI.
	ListZoneSpecs(ctx context.Context, in *ListZoneSpecsRequest, opts ...grpc.CallOption) (ZmsUI_ListZoneSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type zmsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewZmsUIClient(cc grpc.ClientConnInterface) ZmsUIClient {
	return &zmsUIClient{cc}
}

func (c *zmsUIClient) ListZoneSpecs(ctx context.Context, in *ListZoneSpecsRequest, opts ...grpc.CallOption) (ZmsUI_ListZoneSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ZmsUI_ServiceDesc.Streams[0], "/v1.ZmsUI/ListZoneSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &zmsUIListZoneSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ZmsUI_ListZoneSpecsClient interface {
	Recv() (*ListZoneSpecsResponse, error)
	grpc.ClientStream
}

type zmsUIListZoneSpecsClient struct {
	grpc.ClientStream
}

func (x *zmsUIListZoneSpecsClient) Recv() (*ListZoneSpecsResponse, error) {
	m := new(ListZoneSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zmsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ZmsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZmsUIServer is the server API for ZmsUI service.
// All implementations must embed UnimplementedZmsUIServer
// for forward compatibility
type ZmsUIServer interface {
	// ListZoneSpecs returns a list of Availability Zone(s) that can be started through the UI.
	ListZoneSpecs(*ListZoneSpecsRequest, ZmsUI_ListZoneSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedZmsUIServer()
}

// UnimplementedZmsUIServer must be embedded to have forward compatible implementations.
type UnimplementedZmsUIServer struct {
}

func (UnimplementedZmsUIServer) ListZoneSpecs(*ListZoneSpecsRequest, ZmsUI_ListZoneSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListZoneSpecs not implemented")
}
func (UnimplementedZmsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedZmsUIServer) mustEmbedUnimplementedZmsUIServer() {}

// UnsafeZmsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZmsUIServer will
// result in compilation errors.
type UnsafeZmsUIServer interface {
	mustEmbedUnimplementedZmsUIServer()
}

func RegisterZmsUIServer(s grpc.ServiceRegistrar, srv ZmsUIServer) {
	s.RegisterService(&ZmsUI_ServiceDesc, srv)
}

func _ZmsUI_ListZoneSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListZoneSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZmsUIServer).ListZoneSpecs(m, &zmsUIListZoneSpecsServer{stream})
}

type ZmsUI_ListZoneSpecsServer interface {
	Send(*ListZoneSpecsResponse) error
	grpc.ServerStream
}

type zmsUIListZoneSpecsServer struct {
	grpc.ServerStream
}

func (x *zmsUIListZoneSpecsServer) Send(m *ListZoneSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ZmsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZmsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ZmsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZmsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZmsUI_ServiceDesc is the grpc.ServiceDesc for ZmsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZmsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ZmsUI",
	HandlerType: (*ZmsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ZmsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListZoneSpecs",
			Handler:       _ZmsUI_ListZoneSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zms-ui.proto",
}
